name: "Fabrice Weinberg"
description: "Just a Blog"

url: "http://blog.weinberg.me"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true


prose:
  siteurl: "http://blog.weinberg.me"
  metadata:
      "_posts": |
        layout: post
        title: "New Title Here"
        published: true