name: "Fabrice Weinberg"
description: "Just a Blog"

url: "http://blog.weinberg.me"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true


prose:
  siteurl: "http://blog.weinberg.me"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element:" text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"
